# ─────────────────────────────────────────────
# alerts.py — Email notification via Gmail SMTP
# ─────────────────────────────────────────────

import os
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText


def _build_html(results: dict) -> str:
    """Builds a clean HTML email body with price band tables."""
    today = datetime.today().strftime("%B %Y")

    html = f"""
    <html><body style="font-family: Arial, sans-serif; max-width: 800px; margin: auto;">
    <h2 style="color: #1a1a2e;">📊 Nifty 500 — Monthly Top Picks</h2>
    <p style="color: #555;">📅 {today} &nbsp;|&nbsp; Minimum hold: 8 months</p>
    <hr/>
    """

    if not results:
        html += "<p>⚠️ No stocks matched the criteria this month.</p>"
    else:
        for band_label, df in results.items():
            html += f"""
            <h3 style="color: #0f3460; border-bottom: 2px solid #0f3460;
                        padding-bottom: 4px;">{band_label}</h3>
            <table style="width:100%; border-collapse: collapse; margin-bottom: 24px;">
                <thead>
                    <tr style="background:#0f3460; color:white; text-align:left;">
                        <th style="padding:8px;">#</th>
                        <th style="padding:8px;">Stock</th>
                        <th style="padding:8px;">Buy At</th>
                        <th style="padding:8px;">Target</th>
                        <th style="padding:8px;">ROI %</th>
                        <th style="padding:8px;">Min Hold Until</th>
                        <th style="padding:8px;">Best Sell Date</th>
                        <th style="padding:8px;">Don't Hold Past</th>
                        <th style="padding:8px;">Turnover (Cr)</th>
                        <th style="padding:8px;">Liquidity</th>
                    </tr>
                </thead>
                <tbody>
            """
            for i, row in df.iterrows():
                bg = "#f9f9f9" if i % 2 == 0 else "#ffffff"
                html += f"""
                <tr style="background:{bg};">
                    <td style="padding:8px;">{i + 1}</td>
                    <td style="padding:8px; font-weight:bold;">{row["Stock"]}</td>
                    <td style="padding:8px;">₹{row["Buy_Price"]}</td>
                    <td style="padding:8px;">₹{row["Exit_Target"]}</td>
                    <td style="padding:8px; color:#16a34a; font-weight:bold;">+{row["Weighted_ROI_%"]}%</td>
                    <td style="padding:8px;">{row["Min_Hold_Until"]}</td>
                    <td style="padding:8px; font-weight:bold;">{row["Best_Sell_Date"]}</td>
                    <td style="padding:8px; color:#dc2626;">{row["Forecast_Expires"]}</td>
                    <td style="padding:8px;">₹{row["Avg_Daily_Turnover_Cr"]}</td>
                    <td style="padding:8px;">{row["Liquidity"]}</td>
                </tr>
                """
            html += "</tbody></table>"

    html += """
    <hr/>
    <p style="color:#999; font-size:12px;">
        Generated by Nifty 500 Stock Analyzer &nbsp;|&nbsp;
        Predictions are model-based estimates, not financial advice.
    </p>
    </body></html>
    """
    return html


def send_email_alert(results: dict, debug: bool = False) -> None:
    """
    Sends stock picks as a formatted HTML email via Gmail SMTP.

    Required environment variables:
        GMAIL_SENDER    — your Gmail address (e.g. you@gmail.com)
        GMAIL_PASSWORD  — Gmail App Password (not your login password)
                          Generate at: myaccount.google.com/apppasswords
        GMAIL_RECIPIENT — email address to send to (can be same as sender)
    """
    sender = os.getenv("GMAIL_SENDER", "").strip().strip('"').strip("'")
    password = os.getenv("GMAIL_PASSWORD", "").strip().strip('"').strip("'")
    recipient = os.getenv("GMAIL_RECIPIENT", "").strip().strip('"').strip("'")

    if not all([sender, password, recipient]):
        print(
            "❌ Email credentials missing. Set GMAIL_SENDER, GMAIL_PASSWORD, GMAIL_RECIPIENT."
        )
        return

    if debug:
        print(f"  Sender    : {sender}")
        print(f"  Recipient : {recipient}")
        print(f"  Password  : {'*' * len(password)}")

    today = datetime.today().strftime("%B %Y")
    subject = f"📊 Nifty 500 Top Picks — {today}"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = recipient
    msg.attach(MIMEText(_build_html(results), "html"))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(sender, password)
            server.sendmail(sender, recipient, msg.as_string())
        print("✅ Email sent successfully!")
    except smtplib.SMTPAuthenticationError:
        print("❌ Gmail authentication failed — check GMAIL_SENDER and GMAIL_PASSWORD.")
        print(
            "   Make sure you're using an App Password, not your Gmail login password."
        )
        print("   Generate one at: https://myaccount.google.com/apppasswords")
    except Exception as e:
        print(f"❌ Failed to send email: {e}")
